services:
  - type: web
    name: crisp-checker-app
    env: docker
    plan: free
    region: oregon  # You can change to frankfurt if you prefer Europe
    branch: main
    repo: https://github.com/FernandoRFNery/CrispChecker
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - "**/*"
    autoDeploy: true
